# Setup dependabot.yml file for both client and server dependencies

version: 2
updates:
  - package-ecosystem: "npm" 
    directory: "/Client"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/Server" 
    schedule:
      interval: "weekly"
